### ISSUE TITLE
How to run it

### ISSUE THREAD

**Issue by jamillieJaso** [wcbeard/Authorship-Attribution#1]
Hello can you describe how it works and how I should use it I don’t have any idea what to open first and what second, should I specify folder with text or no? Please if you can describe it in details. Thanks in advance!

**Comment by wcbeard** [comment]
Sorry, this was very long ago and I don't have a good memory of what the setup was. It looks like it uses an older version of python as well, so I'm not sure if it could even run anymore. I believe I put text files in some directory, though.

**Comment by jamillieJaso** [comment]
Thx
